16:03:24,858 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred.
16:03:25,361 DEBUG org.springframework.jdbc.core.JdbcTemplate:528 - Executing SQL update [CREATE TABLE CUSTOMER(CUSTOMER_ID VARCHAR(20), COMPANY_NAME VARCHAR(50), EMAIL VARCHAR(50), TELEPHONE VARCHAR(20), NOTES VARCHAR(255))]
16:03:25,365 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:25,765 TRACE hsqldb.db.HSQLDB4B30DE19D8.ENGINE:? - log close size: 37
16:03:26,063  INFO hsqldb.db.HSQLDB4B30DE19D8.ENGINE:? - Database closed
16:03:26,232 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,271  INFO org.springframework.jdbc.support.SQLErrorCodesFactory:126 - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase]
16:03:26,272 DEBUG org.springframework.jdbc.support.SQLErrorCodesFactory:199 - Looking up default SQLErrorCodes for DataSource [org.apache.commons.dbcp.BasicDataSource@49049a04]
16:03:26,272 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,274 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,274 DEBUG org.springframework.jdbc.support.SQLErrorCodesFactory:217 - Database product name cached for DataSource [org.apache.commons.dbcp.BasicDataSource@49049a04]: name is 'HSQL Database Engine'
16:03:26,275 DEBUG org.springframework.jdbc.support.SQLErrorCodesFactory:175 - SQL error codes for 'HSQL Database Engine' found
16:03:26,276 DEBUG org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator:281 - Unable to translate SQLException with Error code '-5504', will now try the fallback translator
16:03:26,277 DEBUG org.springframework.jdbc.core.JdbcTemplate:528 - Executing SQL update [CREATE TABLE TBL_CALL(NOTES VARCHAR(255), TIME_AND_DATE DATE, CUSTOMER_ID VARCHAR(20))]
16:03:26,277 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,278 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,278 DEBUG org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator:281 - Unable to translate SQLException with Error code '-5504', will now try the fallback translator
16:03:26,302 DEBUG org.springframework.jdbc.core.JdbcTemplate:528 - Executing SQL update [CREATE TABLE ACTION (ACTION_ID integer generated by default as identity (start with 1), DETAILS VARCHAR(255), COMPLETE BOOLEAN, OWNING_USER VARCHAR(20), REQUIRED_BY DATE)]
16:03:26,302 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,302 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,302 DEBUG org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator:281 - Unable to translate SQLException with Error code '-5504', will now try the fallback translator
16:03:26,327 DEBUG org.springframework.jdbc.core.JdbcTemplate:906 - Executing prepared SQL update
16:03:26,328 DEBUG org.springframework.jdbc.core.JdbcTemplate:625 - Executing prepared SQL statement [INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)]
16:03:26,328 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,405 DEBUG org.springframework.jdbc.core.JdbcTemplate:916 - SQL update affected 1 rows
16:03:26,407 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,414 DEBUG org.springframework.jdbc.core.JdbcTemplate:691 - Executing prepared SQL query
16:03:26,414 DEBUG org.springframework.jdbc.core.JdbcTemplate:625 - Executing prepared SQL statement [SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = ?]
16:03:26,415 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,422 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,426 DEBUG org.springframework.jdbc.core.JdbcTemplate:691 - Executing prepared SQL query
16:03:26,426 DEBUG org.springframework.jdbc.core.JdbcTemplate:625 - Executing prepared SQL statement [SELECT ACTION_ID, DETAILS, COMPLETE, OWNING_USER, REQUIRED_BY FROM ACTION WHERE OWNING_USER=? AND COMPLETE=?]
16:03:26,426 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:110 - Fetching JDBC Connection from DataSource
16:03:26,428 DEBUG org.springframework.jdbc.datasource.DataSourceUtils:327 - Returning JDBC Connection to DataSource
16:03:26,494 TRACE hsqldb.db.HSQLDB4B30DE19D8.ENGINE:? - log close size: 118
16:03:26,780  INFO hsqldb.db.HSQLDB4B30DE19D8.ENGINE:? - Database closed
16:07:02,874 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred.
16:30:58,434 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
16:31:31,618 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
16:32:15,889 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
16:32:29,572 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
16:40:13,620 ERROR com.virtualpairprogrammers.client.SimpleClientTest:27 - Some error occurred
16:40:15,129 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
11:52:03,619 ERROR com.virtualpairprogrammers.client.SimpleClientTest:27 - Some error occurred
11:52:05,661 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
12:16:49,850 ERROR com.virtualpairprogrammers.client.SimpleClientTest:27 - Some error occurred
12:16:51,374 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:39 - The number of records was 163
12:44:52,370 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred
12:44:54,005 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:38 - The number of records was 163
13:12:09,077 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred
13:12:10,690 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:38 - The number of records was 163
13:49:20,443 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred
13:49:21,931 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:38 - The number of records was 163
16:05:15,644 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred
16:06:16,311 ERROR com.virtualpairprogrammers.client.SimpleClientTest:26 - Some error occurred
16:06:17,783 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:38 - The number of records was 163
16:34:49,715 ERROR com.virtualpairprogrammers.client.SimpleClientTest:29 - Some error occurred
16:34:51,327 DEBUG com.virtualpairprogrammers.client.SimpleClientTest:41 - The number of records was 163
